router_id: 4.4.4.4
asn: 65004
interfaces:
  - name: ethernet-1/1
    ip: 20.1.1.2/24
  - name: ethernet-1/2
    ip: 30.1.1.1/24
  - name: ethernet-1/3
    ip: 50.1.1.2/24

bgp_neighbors:
  - neighbor_ip: 20.1.1.1
    peer_asn: 65003
  - neighbor_ip: 30.1.1.2
    peer_asn: 65001
  - neighbor_ip: 50.1.1.1
    peer_asn: 65002
