router_id: 2.2.2.2
asn: 65002
interfaces:
  - name: ethernet-1/1
    ip: 40.1.1.2/24
  - name: ethernet-1/2
    ip: 10.1.1.1/24
  - name: ethernet-1/3
    ip: 50.1.1.1/24

bgp_neighbors:
  - neighbor_ip: 40.1.1.1
    peer_asn: 65001
  - neighbor_ip: 10.1.1.2
    peer_asn: 65003
  - neighbor_ip: 50.1.1.2
    peer_asn: 65004
