---
- name: Configure OSPF on Cisco Routers
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    # STEP 1: Bind Interfaces into OSPF
    - name: OSPF Interfaces for R1
      cisco.ios.ios_ospf_interfaces:
        config:
          - name: Ethernet1/0
            address_family:
              - afi: ipv4
                process:
                  id: 1
                  area_id: 0
          - name: Loopback0
            address_family:
              - afi: ipv4
                process:
                  id: 1
                  area_id: 0
        state: merged
      when: inventory_hostname == "R1"

    - name: OSPF Interfaces for R2
      cisco.ios.ios_ospf_interfaces:
        config:
          - name: Ethernet1/0
            address_family:
              - afi: ipv4
                process:
                  id: 1
                  area_id: 0
          - name: Ethernet2/0
            address_family:
              - afi: ipv4
                process:
                  id: 1
                  area_id: 0
        state: merged
      when: inventory_hostname == "R2"

    - name: OSPF Interfaces for R3
      cisco.ios.ios_ospf_interfaces:
        config:
          - name: Ethernet2/0
            address_family:
              - afi: ipv4
                process:
                  id: 1
                  area_id: 0
          - name: Loopback0
            address_family:
              - afi: ipv4
                process:
                  id: 1
                  area_id: 0
        state: merged
      when: inventory_hostname == "R3"

    - name: Configure OSPFv2 Process on R1
      cisco.ios.ios_ospfv2:
        config:
          processes:
            - process_id: 1
              router_id: 1.1.1.1
              network:
                - address: 10.0.0.0
                  wildcard_bits: 0.255.255.255
                  area: 0
                - address: 1.1.1.1
                  wildcard_bits: 0.0.0.0
                  area: 0
        state: merged
      when: inventory_hostname == "R1"

    - name: Configure OSPFv2 Process on R2
      cisco.ios.ios_ospfv2:
        config:
          processes:
            - process_id: 1
              router_id: 20.0.0.1
              network:
                - address: 10.0.0.0
                  wildcard_bits: 0.255.255.255
                  area: 0
                - address: 20.0.0.0
                  wildcard_bits: 0.255.255.255
                  area: 0
        state: merged
      when: inventory_hostname == "R2"

    - name: Configure OSPFv2 Process on R3
      cisco.ios.ios_ospfv2:
        config:
          processes:
            - process_id: 1
              router_id: 2.2.2.2
              network:
                - address: 20.0.0.0
                  wildcard_bits: 0.255.255.255
                  area: 0
                - address: 2.2.2.2
                  wildcard_bits: 0.0.0.0
                  area: 0
        state: merged
      when: inventory_hostname == "R3"



