- name: Verify BGP routing on all routers
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Show BGP summary
      arista.eos.eos_command:
        commands:
          - show ip bgp summary
      register: bgp_summary

    - name: Show BGP routes
      arista.eos.eos_command:
        commands:
          - show ip bgp
      register: bgp_routes

    - name: Show IP routing table
      arista.eos.eos_command:
        commands:
          - show ip route
      register: routing_table

    - name: Ping R3 loopback from R1
      arista.eos.eos_command:
        commands:
          - ping 2.2.2.2 source 1.1.1.1
      when: inventory_hostname == "R1"
      register: ping_r3_from_r1

    - name: Ping R1 loopback from R3
      arista.eos.eos_command:
        commands:
          - ping 1.1.1.1 source 2.2.2.2
      when: inventory_hostname == "R3"
      register: ping_r1_from_r3

    - name: Print verification results
      debug:
        msg:
          - "=== BGP Summary ==="
          - "{{ bgp_summary.stdout_lines }}"
          - "=== BGP Routes ==="
          - "{{ bgp_routes.stdout_lines }}"
          - "=== IP Routing Table ==="
          - "{{ routing_table.stdout_lines }}"
          - "=== Ping Test (if run) ==="
          - "{{ ping_r3_from_r1.stdout_lines | default([]) + ping_r1_from_r3.stdout_lines | default([]) }}"
