---
- name: Configure interfaces and static routes on Cisco routers
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Add static route on R1 to reach R3 via R2
      cisco.ios.ios_static_routes:
        config:
          - address_families:
              - afi: ipv4
                routes:
                  - dest: 2.2.2.2/32
                    next_hops:
                      - forward_router_address: 10.0.0.2
        state: merged
      when: inventory_hostname == "R1"

    - name: Add static route on R2 to reach R3's loopback
      cisco.ios.ios_static_routes:
        config:
          - address_families:
              - afi: ipv4
                routes:
                  - dest: 2.2.2.2/32
                    next_hops:
                      - forward_router_address: 20.0.0.2
        state: merged
      when: inventory_hostname == "R2"

    - name: Add return route on R2 to reach R1's loopback
      cisco.ios.ios_static_routes:
        config:
          - address_families:
              - afi: ipv4
                routes:
                  - dest: 1.1.1.1/32
                    next_hops:
                      - forward_router_address: 10.0.0.1
        state: merged
      when: inventory_hostname == "R2"

    - name: Add return route on R3 to reach R1's loopback
      cisco.ios.ios_static_routes:
        config:
          - address_families:
              - afi: ipv4
                routes:
                  - dest: 1.1.1.1/32
                    next_hops:
                      - forward_router_address: 20.0.0.1
        state: merged
      when: inventory_hostname == "R3"