services:
  gnmic:
    image: ghcr.io/openconfig/gnmic:latest
    command: ["subscribe", "--config", "/conf/gnmic.yml"]
    volumes:
      - ./gnmic.yml:/conf/gnmic.yml
    ports:
      - "9804:9804"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3300:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
  
volumes:
  grafana-storage:
