---
- name: Deploy OSPFv2 across the Arista 4-node square
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Enable global IP routing
      arista.eos.eos_config:
        lines:
          - ip routing

    - name: Configure OSPFv2 process on R1
      arista.eos.eos_ospfv2:
        config:
          processes:
            - process_id: 1
              router_id: 1.1.1.1
              networks:
                - prefix: 1.0.0.0/8    # Loopback1
                  area:   "0.0.0.0"
                - prefix: 20.0.0.0/8   # R1–R2 link
                  area:   "0.0.0.0"
                - prefix: 10.0.0.0/8   # R1–R4 link
                  area:   "0.0.0.0"
        state: merged
      when: inventory_hostname == "R1"

    - name: Configure OSPFv2 process on R2
      arista.eos.eos_ospfv2:
        config:
          processes:
            - process_id: 1
              router_id: 20.0.0.2
              networks:
                - prefix: 20.0.0.0/8           # R2–R1
                  area: "0.0.0.0"
                - prefix: 30.0.0.0/8           # R2–R3
                  area: "0.0.0.0"
        state: merged
      when: inventory_hostname == "R2"

    - name: Configure OSPFv2 process on R3
      arista.eos.eos_ospfv2:
        config:
          processes:
            - process_id: 1
              router_id: 2.2.2.2
              networks:
                - prefix:  2.0.0.0/8   # Loopback1
                  area:    "0.0.0.0"
                - prefix: 30.0.0.0/8   # R3–R2
                  area:    "0.0.0.0"
                - prefix: 40.0.0.0/8   # R3–R4
                  area:    "0.0.0.0"
        state: merged
      when: inventory_hostname == "R3"

    - name: Configure OSPFv2 process on R4
      arista.eos.eos_ospfv2:
        config:
          processes:
            - process_id: 1
              router_id: 10.0.0.2
              networks:
                - prefix: 40.0.0.0/8           # R4–R3
                  area: "0.0.0.0"
                - prefix: 10.0.0.0/8           # R4–R1
                  area: "0.0.0.0"
        state: merged
      when: inventory_hostname == "R4"


    - name: R1 – tie Eth1 & Eth4 into OSPF area 0
      arista.eos.eos_ospf_interfaces:
        config:
          - name: Ethernet1
            address_family:
              - afi: ipv4
                area:
                  area_id: "0.0.0.0"
                cost: 10
                network: point-to-point
          - name: Ethernet4
            address_family:
              - afi: ipv4
                area:
                  area_id: "0.0.0.0"
                cost: 10
                network: point-to-point
        state: merged
      when: inventory_hostname == "R1"

    - name: R2 – tie Eth1 & Eth2 into OSPF area 0
      arista.eos.eos_ospf_interfaces:
        config:
          - name: Ethernet1
            address_family:
              - afi: ipv4
                area:
                  area_id: "0.0.0.0"
                cost: 10
                network: point-to-point
          - name: Ethernet2
            address_family:
              - afi: ipv4
                area:
                  area_id: "0.0.0.0"
                cost: 10
                network: point-to-point
        state: merged
      when: inventory_hostname == "R2"

    - name: R3 – tie Eth2 & Eth3 into OSPF area 0
      arista.eos.eos_ospf_interfaces:
        config:
          - name: Ethernet2
            address_family:
              - afi: ipv4
                area:
                  area_id: "0.0.0.0"
                cost: 10
                network: point-to-point
          - name: Ethernet3
            address_family:
              - afi: ipv4
                area:
                  area_id: "0.0.0.0"
                cost: 10
                network: point-to-point
        state: merged
      when: inventory_hostname == "R3"

    - name: R4 – tie Eth3 & Eth4 into OSPF area 0
      arista.eos.eos_ospf_interfaces:
        config:
          - name: Ethernet3
            address_family:
              - afi: ipv4
                area:
                  area_id: "0.0.0.0"
                cost: 10
                network: point-to-point
          - name: Ethernet4
            address_family:
              - afi: ipv4
                area:
                  area_id: "0.0.0.0"
                cost: 10
                network: point-to-point
        state: merged
      when: inventory_hostname == "R4"

    - name: Verify OSPF neighbor adjacencies
      arista.eos.eos_command:
        commands:
          - show ip ospf neighbor
      register: ospf_neighbors

    - name: Display OSPF neighbor table
      debug:
        var: ospf_neighbors.stdout_lines
